# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/ai_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/ai_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/ai_service.proto\x12\x02\x61i\"\xab\x01\n\x0b\x44\x61taRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x16\n\x0eoperation_time\x18\x02 \x01(\x02\x12\x14\n\x0crotation_rpm\x18\x03 \x01(\x02\x12\x15\n\rpower_consume\x18\x04 \x01(\x02\x12\x14\n\x0cmagnet_avail\x18\x05 \x01(\x08\x12\x17\n\x0fmagnet_strength\x18\x06 \x01(\x02\x12\x15\n\rmagnet_active\x18\x07 \x01(\x08\"T\n\x0c\x44\x61taResponse\x12\x14\n\x0crotation_rpm\x18\x01 \x01(\x02\x12\x17\n\x0fmagnet_strength\x18\x02 \x01(\x02\x12\x15\n\rmagnet_active\x18\x03 \x01(\x08\x32=\n\tAIService\x12\x30\n\x0b\x41nalyzeData\x12\x0f.ai.DataRequest\x1a\x10.ai.DataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAREQUEST']._serialized_start=31
  _globals['_DATAREQUEST']._serialized_end=202
  _globals['_DATARESPONSE']._serialized_start=204
  _globals['_DATARESPONSE']._serialized_end=288
  _globals['_AISERVICE']._serialized_start=290
  _globals['_AISERVICE']._serialized_end=351
# @@protoc_insertion_point(module_scope)
